chore: add check for image pull error

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -166,6 +166,7 @@ jobs:
           graylogHost: graylog-service
           graylogPort: 9000
         EOF
+      shell: bash
 
     - name: Install Qubership Logging Operator
       run: |
@@ -186,9 +187,10 @@ jobs:
         max_attempts=${{ env.max_attempts }}
         while [[ $attempt -le $max_attempts ]]; do
           echo "Attempt $attempt/$max_attempts: Checking logging-operator pod status..."
-          phase=$(kubectl get pod -l name=logging-service-operator -n ${{ env.namespace }} -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo "NotFound")
-          ready=$(kubectl get pod -l name=logging-service-operator -n ${{ env.namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "NotFound")
-          scheduled=$(kubectl get pod -l name=logging-service-operator -n ${{ env.namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="PodScheduled")].status}' 2>/dev/null || echo "NotFound")
+          pod=$(kubectl get pod -l name=logging-service-operator -n ${{ env.namespace }} -o jsonpath='{.items[0]}')
+          phase=$(echo "$pod" | jq -r '.status.phase')
+          ready=$(echo "$pod" | jq -r '.status.conditions[] | select(.type == "Ready") | .status')
+          scheduled=$(echo "$pod" | jq -r '.status.conditions[] | select(.type == "PodScheduled") | .status')
           if [[ "$ready" == "True" ]]; then
             echo "Logging operator is ready."
             break
@@ -197,13 +199,19 @@ jobs:
             sleep ${{ env.delay }}
             ((attempt++))
           elif [[ "$phase" == "Pending" && "$scheduled" == "True" ]]; then
-            echo "Logging operator status: $phase. Retrying in ${{ env.delay }} seconds..."
-            sleep ${{ env.delay }}
-            ((attempt++))
+            images=$(echo "$pod" | jq -r '.status.containerStatuses[] | select(.state.waiting.reason == "ImagePullBackOff") | .image' 2>/dev/null)
+            if [[ -n  "$images" ]]; then
+              echo -e "ERROR: Some images cannot be pulled:\n$images"
+              exit 1
+            else
+              echo "Logging operator status: $phase. Retrying in ${{ env.delay }} seconds..."
+              sleep ${{ env.delay }}
+              ((attempt++))
+            fi
           else
-            echo "Logging operator status: $phase"
-            operator_pod=$(kubectl get pod -l name=logging-service-operator -n ${{ env.namespace }} -o jsonpath='{.items[0]}' -o custom-columns=":metadata.name" --no-headers)
-            kubectl events -n ${{ env.namespace }} --for pod/"$operator_pod"
+            pod_events=$(kubectl events -n ${{ env.namespace }} --for pod/"$(echo $pod | jq -r '.metadata.name')")
+            echo -e "Events for logging operator pod:\n$pod_events"
+            echo -e "Pods status in ${{ env.namespace }} namespace:\n$(kubectl get pods -n ${{ env.namespace }})"
             exit 1
           fi
         done
@@ -222,9 +230,10 @@ jobs:
         max_attempts=${{ env.max_attempts }}
         while [[ $attempt -le $max_attempts ]]; do
           echo "Attempt $attempt/$max_attempts: Checking graylog pod status..."
-          phase=$(kubectl get pod -l name=graylog -n ${{ env.namespace }} -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo "NotFound")
-          ready=$(kubectl get pod -l name=graylog -n ${{ env.namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "NotFound")
-          scheduled=$(kubectl get pod -l name=graylog -n ${{ env.namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="PodScheduled")].status}' 2>/dev/null || echo "NotFound")
+          pod=$(kubectl get pod -l name=graylog -n ${{ env.namespace }} -o jsonpath='{.items[0]}')
+          phase=$(echo "$pod" | jq -r '.status.phase')
+          ready=$(echo "$pod" | jq -r '.status.conditions[] | select(.type == "Ready") | .status')
+          scheduled=$(echo "$pod" | jq -r '.status.conditions[] | select(.type == "PodScheduled") | .status')
           if [[ "$ready" == "True" ]]; then
             echo "Graylog is ready."
             break
@@ -233,13 +242,19 @@ jobs:
             sleep ${{ env.delay }}
             ((attempt++))
           elif [[ "$phase" == "Pending" && "$scheduled" == "True" ]]; then
-            echo "Graylog status: $phase. Retrying in ${{ env.delay }} seconds..."
-            sleep ${{ env.delay }}
-            ((attempt++))
+            images=$(echo "$pod" | jq -r '.status.containerStatuses[] | select(.state.waiting.reason == "ImagePullBackOff") | .image' 2>/dev/null)
+            if [[ -n  "$images" ]]; then
+              echo -e "ERROR: Some images cannot be pulled:\n$images"
+              exit 1
+            else
+              echo "Graylog status: $phase. Retrying in ${{ env.delay }} seconds..."
+              sleep ${{ env.delay }}
+              ((attempt++))
+            fi
           else
-            echo "Graylog status: $phase"
-            graylog_pod=$(kubectl get pod -l name=graylog -n ${{ env.namespace }} -o jsonpath='{.items[0]}' -o custom-columns=":metadata.name" --no-headers)
-            kubectl events -n ${{ env.namespace }} --for pod/"$graylog_pod"
+            pod_events=$(kubectl events -n ${{ env.namespace }} --for pod/"$(echo $pod | jq -r '.metadata.name')")
+            echo -e "Events for graylog pod:\n$pod_events"
+            echo -e "Pods status in ${{ env.namespace }} namespace:\n$(kubectl get pods -n ${{ env.namespace }})"
             exit 1
           fi
         done
@@ -251,14 +266,15 @@ jobs:
 
     - name: Check integration tests status
       run: |
-        echo "Checking status of integration tests..."
+        echo "Checking status of integration tests pod..."
         attempt=1
         max_attempts=${{ env.max_attempts }}
         while [[ $attempt -le $max_attempts ]]; do
           echo "Attempt $attempt/$max_attempts: Checking integration-tests pod status..."
-          phase=$(kubectl get pod -l name=logging-integration-tests-runner -n ${{ env.namespace }} -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo "NotFound")
-          ready=$(kubectl get pod -l name=logging-integration-tests-runner -n ${{ env.namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "NotFound")
-          scheduled=$(kubectl get pod -l name=logging-integration-tests-runner -n ${{ env.namespace }} -o jsonpath='{.items[0].status.conditions[?(@.type=="PodScheduled")].status}' 2>/dev/null || echo "NotFound")
+          pod=$(kubectl get pod -l name=logging-integration-tests-runner -n ${{ env.namespace }} -o jsonpath='{.items[0]}')
+          phase=$(echo "$pod" | jq -r '.status.phase')
+          ready=$(echo "$pod" | jq -r '.status.conditions[] | select(.type == "Ready") | .status')
+          scheduled=$(echo "$pod" | jq -r '.status.conditions[] | select(.type == "PodScheduled") | .status')
           if [[ "$ready" == "True" ]]; then
             echo "Integration tests pod is ready."
             break
@@ -267,13 +283,19 @@ jobs:
             sleep ${{ env.delay }}
             ((attempt++))
           elif [[ "$phase" == "Pending" && "$scheduled" == "True" ]]; then
-            echo "Integration tests pod status: $phase. Retrying in ${{ env.delay }} seconds..."
-            sleep ${{ env.delay }}
-            ((attempt++))
+            images=$(echo "$pod" | jq -r '.status.containerStatuses[] | select(.state.waiting.reason == "ImagePullBackOff") | .image' 2>/dev/null)
+            if [[ -n  "$images" ]]; then
+              echo -e "ERROR: Some images cannot be pulled:\n$images"
+              exit 1
+            else
+              echo "Integration tests pod status: $phase. Retrying in ${{ env.delay }} seconds..."
+              sleep ${{ env.delay }}
+              ((attempt++))
+            fi
           else
-            echo "Integration tests pod status: $phase"
-            tests_pod=$(kubectl get pod -l name=logging-integration-tests-runner -n ${{ env.namespace }} -o jsonpath='{.items[0]}' -o custom-columns=":metadata.name" --no-headers)
-            kubectl events -n ${{ env.namespace }} --for pod/"$tests_pod"
+            pod_events=$(kubectl events -n ${{ env.namespace }} --for pod/"$(echo $pod | jq -r '.metadata.name')")
+            echo -e "Events for integration tests pod:\n$pod_events"
+            echo -e "Pods status in ${{ env.namespace }} namespace:\n$(kubectl get pods -n ${{ env.namespace }})"
             exit 1
           fi
         done
@@ -309,8 +331,8 @@ jobs:
                 exit 1
               fi
             else
-              echo "Smoke test in not completed yet. Checking in $delay seconds..."
-              sleep $delay
+              echo "Smoke test is not completed yet. Checking in ${{ env.delay }} seconds..."
+              sleep ${{ env.delay }}
               ((attempt++))
             fi
           elif [[ -n $(echo "$logs" | grep -E "Test Indexer Cluster Status.*PASS") ]]; then
@@ -321,13 +343,13 @@ jobs:
               echo "Smoke test passed."
               exit 0
             else
-              echo "Smoke test is not completed yet. Checking in $delay seconds..."
-              sleep $delay
+              echo "Smoke test is not completed yet. Checking in ${{ env.delay }} seconds..."
+              sleep ${{ env.delay }}
               ((attempt++))
             fi
           else
-            echo "Smoke test is not completed yet. Checking in $delay seconds..."
-            sleep $delay
+            echo "Smoke test is not completed yet. Checking in ${{ env.delay }} seconds..."
+            sleep ${{ env.delay }}
             ((attempt++))
           fi
         done
